version: "3"
services:
  db:
    image: mysql:latest
    container_name: forum-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=db_forum
    volumes:
      - ./mysql_db:/var/lib/mysql
