version: "3"
services:
  db:
    image: mysql:latest
    container_name: forum-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_forum
      MYSQL_USER: forum
      MYSQL_PASSWORD: forum
    ports:
      - "3306:3306"
    volumes:
      - /Users/ewa/Documents/Coding/Backend/GOLANG/mysql_db:/var/lib/mysql
